FROM nginx:latest

# RUN rm /etc/nginx/conf.d/default.conf
COPY ./nginx/conf/default.conf /etc/nginx/conf.d/default.conf
COPY ./staticfiles /static/
COPY ./nginx/50x.html /usr/share/nginx/html/50x.html
COPY ./nginx/404.html /usr/share/nginx/html/404.html
