name: ESLint

on: [push]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: stefanoeb/eslint-action@1.0.2
      - name: Install dependencies
        run: |
          npm install eslint
      - name: Run ESLint
        run: eslint . --ext .js
